### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by qvchoq** [tuchkovdima/tuchkovBank#1]
1. В Downloader.java вынести повторяющиейся переменные вне методов
2. В First.java разобраться с потоками (thread)
3. Распределить классы по пакетам, согласно MVC pattern.
4. Ренейминг функций для того чтобы можно было понять, что выполняет функция
5. Добавить readme.md 
6. Ренейминг activities в res/layout/
7. Если не предусмотрена функция ротации экрана, запретить эту возможность

**Comment by tuchkovdima** [comment]
Исправлено
